module.exports = [
  {
    date: "January 4",
    trans: "Whole Foods",
    amount: -80.19,
    type: "Personal",
    category: "Groceries",
    description: "family visit",
    tags: "food",
  },
  {
    date: "January 19",
    trans: "Target",
    amount: -60.1,
    type: "Personal",
    category: "Household",
    description: "misc",
    tags: "",
  },
  {
    date: "January 11",
    trans: "ADP",
    amount: 2478.03,
    type: "Personal",
    category: "Income",
    description: "",
    tags: "",
  },
  {
    date: "January 7",
    trans: "Buffalo Exchange",
    amount: -94.07,
    type: "Personal",
    category: "Clothes",
    description: "Josie's Bachelorette Party",
    tags: "",
  },
  {
    date: "January 14",
    trans: "H&M",
    amount: -180.03,
    type: "Split",
    category: "Clothes",
    description: "Office Attire",
    tags: "misc",
  },
  {
    date: "January 04",
    trans: "Trader Joe's",
    amount: -88.23,
    type: "Personal",
    category: "Groceries",
    description: "",
    tags: "",
  },
  {
    date: "January 21",
    trans: "Walmart",
    amount: -180.19,
    type: "Business",
    category: "Misc",
    description: "stationery, stereo",
    tags: "",
  },
  {
    date: "January 28",
    trans: "Sammy's Sandwiches",
    amount: -280.19,
    type: "Business",
    category: "Restaurant",
    description: "Takeout for lunch meeting",
    tags: "client, Reynolds",
  },
];
